/* S/390-64 gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 1991, 1993, 1994, 2000-2023 Free Software Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of either:

  * the GNU Lesser General Public License as published by the Free
    Software Foundation; either version 3 of the License, or (at your
    option) any later version.

or

  * the GNU General Public License as published by the Free Software
    Foundation; either version 2 of the License, or (at your option) any
    later version.

or both in parallel, as here.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received copies of the GNU General Public License and the
GNU Lesser General Public License along with the GNU MP Library.  If not,
see https://www.gnu.org/licenses/.  */

#define GMP_LIMB_BITS 64
#define GMP_LIMB_BYTES 8

/* 3900 MHz z15 */
/* Generated by tuneup.c, 2023-07-29, gcc 13.2 */

#define DIVREM_1_NORM_THRESHOLD          MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD           75
#define MOD_1_1P_METHOD                      2  /* 24.60% faster than 1 */
#define MOD_1_NORM_THRESHOLD                22
#define MOD_1_UNNORM_THRESHOLD              27
#define MOD_1N_TO_MOD_1_1_THRESHOLD         14
#define MOD_1U_TO_MOD_1_1_THRESHOLD         13
#define MOD_1_1_TO_MOD_1_2_THRESHOLD         0  /* never mpn_mod_1_1p */
#define MOD_1_2_TO_MOD_1_4_THRESHOLD        37
#define PREINV_MOD_1_TO_MOD_1_THRESHOLD     15
#define USE_PREINV_DIVREM_1                  1
#define DIV_QR_1N_PI1_METHOD                 3  /* 20.39% faster than 1 */
#define DIV_QR_1_NORM_THRESHOLD             37
#define DIV_QR_1_UNNORM_THRESHOLD        MP_SIZE_T_MAX  /* never */
#define DIV_QR_2_PI2_THRESHOLD              20
#define DIVEXACT_1_THRESHOLD                 0  /* always */
#define BMOD_1_TO_MOD_1_THRESHOLD           21

#define DIV_1_VS_MUL_1_PERCENT             547

#define MUL_TOOM22_THRESHOLD                28
#define MUL_TOOM33_THRESHOLD                77
#define MUL_TOOM44_THRESHOLD               232
#define MUL_TOOM6H_THRESHOLD               306
#define MUL_TOOM8H_THRESHOLD               418

#define MUL_TOOM32_TO_TOOM43_THRESHOLD     137
#define MUL_TOOM32_TO_TOOM53_THRESHOLD     148
#define MUL_TOOM42_TO_TOOM53_THRESHOLD     154
#define MUL_TOOM42_TO_TOOM63_THRESHOLD     153
#define MUL_TOOM43_TO_TOOM54_THRESHOLD     208

#define SQR_BASECASE_THRESHOLD               6
#define SQR_TOOM2_THRESHOLD                 38
#define SQR_TOOM3_THRESHOLD                 90
#define SQR_TOOM4_THRESHOLD                220
#define SQR_TOOM6_THRESHOLD                294
#define SQR_TOOM8_THRESHOLD                348

#define MULMID_TOOM42_THRESHOLD             66

#define MULMOD_BNM1_THRESHOLD               21
#define SQRMOD_BNM1_THRESHOLD               15

#define MUL_FFT_MODF_THRESHOLD             344  /* k = 5 */
#define MUL_FFT_TABLE3                                      \
  { {    344, 5}, {     19, 6}, {     10, 5}, {     21, 6}, \
    {     21, 7}, {     11, 6}, {     23, 7}, {     24, 8}, \
    {     13, 7}, {     27, 8}, {     15, 7}, {     31, 8}, \
    {     17, 7}, {     35, 8}, {     21, 9}, {     11, 8}, \
    {     27, 9}, {     15, 8}, {     35, 9}, {     19, 8}, \
    {     39, 9}, {     23, 8}, {     47, 9}, {     27,10}, \
    {     15, 9}, {     39,10}, {     23, 9}, {     51,11}, \
    {     15,10}, {     31, 9}, {     67,10}, {     39, 9}, \
    {     83,10}, {     47,11}, {     31,10}, {     79,11}, \
    {     47,10}, {     95,12}, {     31,11}, {     63,10}, \
    {    127, 9}, {    255, 8}, {    511,10}, {    135,11}, \
    {     79, 9}, {    319, 8}, {    639, 7}, {   1279,10}, \
    {    167,11}, {     95,10}, {    191, 9}, {    383,12}, \
    {     63,11}, {    127,10}, {    255, 9}, {    511,10}, \
    {    271, 9}, {    543,10}, {    287, 9}, {    575, 8}, \
    {   1151,10}, {    319, 9}, {    639,12}, {     95,11}, \
    {    191,10}, {    383,11}, {    207,13}, {     63,12}, \
    {    127,11}, {    255,10}, {    511,11}, {    271,10}, \
    {    543,11}, {    287,10}, {    575, 9}, {   1151,11}, \
    {    319,10}, {    639, 9}, {   1279,11}, {    335,10}, \
    {    671,11}, {    351,12}, {    191,11}, {    383,10}, \
    {    767,11}, {    415,12}, {    223,11}, {    447,10}, \
    {    895,11}, {    479,13}, {    127,12}, {    255,11}, \
    {    511,10}, {   1023,11}, {    543,12}, {    287,11}, \
    {    575,10}, {   1151,12}, {    319,11}, {    639,10}, \
    {   1279,11}, {    671,12}, {    351,13}, {    191,12}, \
    {    383,11}, {    767,12}, {    415,11}, {    831,10}, \
    {   1663,12}, {    447,11}, {    895,12}, {    479,14}, \
    {    127,13}, {    255,12}, {    511,11}, {   1023,12}, \
    {    543,11}, {   1087,10}, {   2175,12}, {    575,11}, \
    {   1151,12}, {    607,13}, {    319,12}, {    639,11}, \
    {   1279,12}, {    671,11}, {   1343,10}, {   2687,13}, \
    {    383,12}, {    767,11}, {   1535,12}, {    831,13}, \
    {    447,12}, {    959,14}, {    255,13}, {    511,12}, \
    {   1087,11}, {   2175,13}, {    575,12}, {   1215,11}, \
    {   2431,13}, {    639,12}, {   1279,13}, {    703,14}, \
    {    383,13}, {    767,12}, {   1535,13}, {    831,12}, \
    {   1663,13}, {    895,12}, {   1791,13}, {    959,15}, \
    {    255,14}, {    511,13}, {   1087,12}, {   2175,13}, \
    {   1215,14}, {  16384,15}, {  32768,16}, {  65536,17}, \
    { 131072,18}, { 262144,19}, { 524288,20}, {1048576,21}, \
    {2097152,22}, {4194304,23}, {8388608,24} }
#define MUL_FFT_TABLE3_SIZE 167
#define MUL_FFT_THRESHOLD                 3008

#define SQR_FFT_MODF_THRESHOLD             276  /* k = 5 */
#define SQR_FFT_TABLE3                                      \
  { {    276, 5}, {     17, 6}, {     10, 5}, {     21, 6}, \
    {     19, 7}, {     10, 6}, {     21, 7}, {     17, 8}, \
    {      9, 7}, {     20, 8}, {     11, 7}, {     23, 8}, \
    {     13, 7}, {     27, 8}, {     19, 9}, {     11, 8}, \
    {     27, 9}, {     15, 8}, {     31, 9}, {     19, 8}, \
    {     39, 9}, {     23, 8}, {     47, 9}, {     27,10}, \
    {     15, 9}, {     39,10}, {     23, 9}, {     47,11}, \
    {     15,10}, {     31, 9}, {     63,10}, {     39, 9}, \
    {     79,10}, {     47,11}, {     31,10}, {     71, 9}, \
    {    143,10}, {     79,11}, {     47,12}, {     31,11}, \
    {     63, 9}, {    255, 8}, {    511, 9}, {    271,11}, \
    {     79,10}, {    159, 9}, {    319, 8}, {    639,10}, \
    {    175,11}, {     95,10}, {    191, 9}, {    383, 8}, \
    {    767,12}, {     63,10}, {    255, 9}, {    511,10}, \
    {    271,11}, {    143,10}, {    287, 9}, {    575,11}, \
    {    159,10}, {    319, 9}, {    639,11}, {    175,12}, \
    {     95,11}, {    191,10}, {    383, 9}, {    767,13}, \
    {     63,11}, {    255,10}, {    511, 9}, {   1023,11}, \
    {    271,10}, {    543,11}, {    287,10}, {    575,12}, \
    {    159,11}, {    319,10}, {    639,11}, {    351,10}, \
    {    703,12}, {    191,11}, {    383,10}, {    767,11}, \
    {    415,12}, {    223,11}, {    447,10}, {    895,11}, \
    {    479,12}, {    255,11}, {    511,10}, {   1023,11}, \
    {    543,12}, {    287,11}, {    575,10}, {   1151,12}, \
    {    319,11}, {    639,10}, {   1279,12}, {    351,11}, \
    {    703,10}, {   1407,13}, {    191,12}, {    383,11}, \
    {    767,12}, {    415,11}, {    831,12}, {    447,11}, \
    {    895,12}, {    479,11}, {    959,13}, {    255,12}, \
    {    511,11}, {   1023,12}, {    543,11}, {   1087,12}, \
    {    575,11}, {   1215,13}, {    319,12}, {    639,11}, \
    {   1279,12}, {    703,11}, {   1407,13}, {    383,12}, \
    {    831,11}, {   1663,13}, {    447,12}, {    895,11}, \
    {   1791,12}, {    959,14}, {    255,13}, {    511,12}, \
    {   1023,11}, {   2175,13}, {    575,12}, {   1215,11}, \
    {   2431,10}, {   4863,13}, {    639,12}, {   1279,13}, \
    {    703,12}, {   1407,11}, {   2815,14}, {    383,13}, \
    {    767,12}, {   1663,13}, {    895,15}, {    255,14}, \
    {    511,13}, {   1087,12}, {   2175,13}, {   1215,12}, \
    {   2431,11}, {   4863,14}, {  16384,15}, {  32768,16}, \
    {  65536,17}, { 131072,18}, { 262144,19}, { 524288,20}, \
    {1048576,21}, {2097152,22}, {4194304,23}, {8388608,24} }
#define SQR_FFT_TABLE3_SIZE 164
#define SQR_FFT_THRESHOLD                 2240

#define MULLO_BASECASE_THRESHOLD             0  /* always */
#define MULLO_DC_THRESHOLD                  30
#define MULLO_MUL_N_THRESHOLD             5895
#define SQRLO_BASECASE_THRESHOLD             4
#define SQRLO_DC_THRESHOLD                 396
#define SQRLO_SQR_THRESHOLD               4292

#define DC_DIV_QR_THRESHOLD                 83
#define DC_DIVAPPR_Q_THRESHOLD             396
#define DC_BDIV_QR_THRESHOLD                72
#define DC_BDIV_Q_THRESHOLD                260

#define INV_MULMOD_BNM1_THRESHOLD           84
#define INV_NEWTON_THRESHOLD               378
#define INV_APPR_THRESHOLD                 378

#define BINV_NEWTON_THRESHOLD              309
#define REDC_1_TO_REDC_2_THRESHOLD          67
#define REDC_2_TO_REDC_N_THRESHOLD          84

#define MU_DIV_QR_THRESHOLD               1258
#define MU_DIVAPPR_Q_THRESHOLD            1470
#define MUPI_DIV_QR_THRESHOLD              142
#define MU_BDIV_QR_THRESHOLD              1099
#define MU_BDIV_Q_THRESHOLD               1421

#define POWM_SEC_TABLE  8,64,126,494,2782

#define GET_STR_DC_THRESHOLD                 8
#define GET_STR_PRECOMPUTE_THRESHOLD        12
#define SET_STR_DC_THRESHOLD               478
#define SET_STR_PRECOMPUTE_THRESHOLD      2407

#define FAC_DSC_THRESHOLD                  216
#define FAC_ODD_THRESHOLD                   58

#define MATRIX22_STRASSEN_THRESHOLD          9
#define HGCD2_DIV1_METHOD                    1  /* 11.50% faster than 3 */
#define HGCD_THRESHOLD                     189
#define HGCD_APPR_THRESHOLD                258
#define HGCD_REDUCE_THRESHOLD             2121
#define GCD_DC_THRESHOLD                   960
#define GCDEXT_DC_THRESHOLD                654
#define JACOBI_BASE_METHOD                   4  /* 35.16% faster than 1 */

/* Tuneup completed successfully, took 5155 seconds */
